Reverting Carlos' commit 899cfc7
This was giving me errors connecting:
AttributeError: 'Connector' object has no attribute 'omero_session_key'
Need to review this logic