Handle multiple calls to omero.config.close()
The previous change in `bin/omero admin reindex` to close
the config early (See #9800) was failing with:

```
^CERROR:ConfigXml:Failed to removed lock file, ignoring
Traceback (most recent call last):
  File ".../lib/python/omero/config.py", line 154, in _close_lock
    os.remove("%s.lock" % self.filename)
OSError: [Errno 2] No such file or direc...
```