Improve error handling of corrupt scripts
The change to Scripts.ice effectively invalidated all
script params stored in the DB. Unders some conditions
(for some users and some scripts), the exceptions raised
in the parse method did not lead to a null JobParams
being returned, but rather to an incomplete one. This
had an odd effect on clients: both insight and web
failed to load the GUI while the CLI died with an exception:
```
  File "lib/python/omero/plugins/script.py", line 513, in print_params
    self.ctx.out("    Type: %s" % v.prototype.ice_staticId())
AttributeError: 'NoneType' object has no attribute 'ice_staticId'
```