Maintain backwards compatibility (See #8266)
By using a new method for the improved (i.e. non-breaking)
invocation, older processors can still talk to newer servers.
If a newer processor is deployed against an older server, than
a NoSuchMethodError will be thrown.

Conflicts:
	components/tools/OmeroPy/test/integration/scriptstest/test_inputs.py